### ISSUE TITLE
the last link in the readme is dead

### ISSUE THREAD

**Issue by aseds** [alanbsmith/pizza-router-demo#1]
[using the api](https://github.com/stevekinney/pizza/blob/master/using_the_api.md)

**Comment by alanbsmith** [comment]
Hey @asdes! Thanks for the catch! Sorry, the docs got reorganized on that repo breaking the link. I'll fix it in a bit when I have access to the repo, but for now here's the link: https://github.com/stevekinney/pizza/blob/master/docs/using_the_api.md

**Comment by alanbsmith** [comment]
@aseds This is now corrected.
